name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'bm-news-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --build-arg GIT_REVISION=$(git rev-parse HEAD) -f ./bm-news-frontend/Dockerfile -t ghcr.io/${{ github.repository_owner }}/bm-news:latest ./bm-news-frontend


      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/your-repository-name:latest

